var path = require('path');
var webpack = require('webpack');

var commonsPlugin = new webpack.optimize.CommonsChunkPlugin('shared.js');
var ExtractTextPlugin = require('extract-text-webpack-plugin');
var TimestampWebpackPlugin = require('timestamp-webpack-plugin');

module.exports ={

  //基础路径(绝对路径)，用来解析entry项
  context: path.resolve('js'),


  //字符串会被解析得到一个module
  //数组中的所有module都会被加载，数组中最后一个module会被导出(export)
  //如果你传一个对象，那么将会生成几个bundle

  entry:{
    index:'./index.js'

  },
  output:{

    //bundle.js存储的真实路径
    path: path.resolve('build/js/'),
    //使用devserver时，浏览器访问bundle.js的虚拟路径
    publicPath:'/public/assets/js/',
    filename: "[name].js"


  },
  plugins:[
    commonsPlugin,
    new ExtractTextPlugin("style.css"),
    new webpack.ProvidePlugin({
      $:'jquery',
      jQuery:'jquery',
      'window.jQuery':'jquery'
    }),
    new webpack.ProvidePlugin({
      'window.Tether':'tether'
    }),
    new TimestampWebpackPlugin({
      path:__dirname,
      filename:'timestamp.json'
    }),
    new webpack.BannerPlugin("****\ngenerated by webpack\n**********\n"),
    new webpack.HotModuleReplacementPlugin()
  ],
  devServer:{
    hot:true,
    inline:true,
    contentBase: 'public'
  },
  //watch:true

  module:{
    preloaders:[
      {
        test:/\.js$/,
        exclude:'node_modules',
        loader:'jshint-loader'
      }
    ],
    loaders:[
      {
        test:/\.(js|es6)$/,
        exclude:/node_modules/,
        loader:"babel-loader"
      },
      {
        test:/\.css$/,
        loader: ExtractTextPlugin.extract("style-loader","css-loader")
      },
      {
        test:/\.scss$/,
        exclude:/node_modules/,
        loader: ExtractTextPlugin.extract("style-loader","css-loader!sass-loader")
      },
      {
        test:/\.(ttf|eot)$/,
        exclude:/node_modules/,
        loader:'url-loader?limit=10000'
      },
      {
        test:/\.(jpg|png)$/,
        loader:'file?name=[path][name].[hash].[ext]'
      },
      // the url-loader uses DataUrls.
      // the file-loader emits files.
      {
        test: /\.woff2?(\?v=[0-9]\.[0-9]\.[0-9])?$/,
        // Limiting the size of the woff fonts breaks font-awesome ONLY for the extract text plugin
        // loader: "url?limit=10000"
        loader: "url"
      },
      {
        test: /\.(ttf|eot|svg)(\?[\s\S]+)?$/,
        loader: 'file'
      }
    ]
  },
  resolve:{
    extensions:['','.js','.es6']
  }
};
